-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 20:28:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sealmeeting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sealmeeting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sealmeeting` DEFAULT CHARACTER SET utf8 ;
USE `sealmeeting` ;

-- -----------------------------------------------------
-- Table `sealmeeting`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmeeting`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NULL,
  `portrait` VARCHAR(128) NULL,
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  UNIQUE INDEX `user_idx` (`uid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmeeting`.`t_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmeeting`.`t_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `name` VARCHAR(64) NULL,
  `portrait` VARCHAR(128) NULL,
  `create_dt` DATETIME NULL,
  `display` VARCHAR(1024) NULL COMMENT 'the current display: teacher, assistant, whiteboard, screen',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `group_idx` (`rid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmeeting`.`t_room_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmeeting`.`t_room_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'room id',
  `uid` VARCHAR(64) NOT NULL COMMENT 'user id',
  `join_dt` DATETIME NULL,
  `role` INT NULL,
  `name` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `camera` TINYINT NULL DEFAULT 1,
  `mic` TINYINT NULL DEFAULT 1,
  UNIQUE INDEX `user_group_idx` (`rid` ASC, `uid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmeeting`.`t_whiteboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmeeting`.`t_whiteboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) NULL COMMENT 'room id',
  `wb_room` VARCHAR(64) NULL COMMENT 'whiteboard room',
  `wbid` VARCHAR(1024) NULL COMMENT 'displayer uri',
  `name` VARCHAR(45) NULL,
  `creator` VARCHAR(64) NULL,
  `pg_count` INT NULL COMMENT '总页数',
  `cur_pg` INT NULL COMMENT '当前页',
  `create_dt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
